In [1]:
# project path setup

import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parent
sys.path.append(str(PROJECT_ROOT))

In [2]:
# imports

from src.data.load_data import load_ratings, load_movies
from src.recommenders.popularity_recommender import PopularityRecommender

In [3]:
# load needed data

DATA_PATH = PROJECT_ROOT / "data" / "raw"

ratings = load_ratings(DATA_PATH)
movies = load_movies(DATA_PATH)

print(ratings.shape)
print(movies.shape)

(32000204, 4)
(87585, 3)

In [4]:
# fit and recommend

pop_rec = PopularityRecommender()
pop_rec.fit(ratings=ratings, movies=movies)

top_10_popular = pop_rec.recommend(top_k=10)
top_10_popular

,movieId,rating_count,title,genres
0,318,102929,"Shawshank Redemption, The (1994)",Crime|Drama
1,356,100296,Forrest Gump (1994),Comedy|Drama|Romance|War
2,296,98409,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
3,2571,93808,"Matrix, The (1999)",Action|Sci-Fi|Thriller
4,593,90330,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller
5,260,85010,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
6,2959,77332,Fight Club (1999),Action|Crime|Drama|Thriller
7,480,75233,Jurassic Park (1993),Action|Adventure|Sci-Fi|Thriller
8,527,73849,Schindler's List (1993),Drama|War
9,4993,73122,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy

In [5]:
# test for the weighted popularity recommender

from src.recommenders.popularity_recommender import WeightedPopularityRecommender

weighted_rec = WeightedPopularityRecommender(min_votes=1000)
weighted_rec.fit(ratings, movies)

weighted_rec.recommend(10)

,movieId,rating_count,avg_rating,weighted_score,title,genres
0,318,102929,4.404614,4.391148,"Shawshank Redemption, The (1994)",Crime|Drama
1,858,66440,4.317030,4.297577,"Godfather, The (1972)",Crime|Drama
2,50,67750,4.265070,4.246743,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
3,1221,43111,4.264468,4.235918,"Godfather: Part II, The (1974)",Crime|Drama
4,527,73849,4.236990,4.220532,Schindler's List (1993),Drama|War
5,2959,77332,4.228780,4.213158,Fight Club (1999),Action|Crime|Drama|Thriller
6,1203,21863,4.265311,4.210190,12 Angry Men (1957),Drama
7,202439,11670,4.312254,4.209083,Parasite (2019),Comedy|Drama
8,296,98409,4.196969,4.184979,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
9,904,24883,4.226701,4.179503,Rear Window (1954),Mystery|Thriller

In [6]:
# testing the window based trending recommender

import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parent
sys.path.append(str(PROJECT_ROOT))

In [7]:
from src.data.load_data import load_ratings, load_movies
from src.recommenders.popularity_recommender import TrendingRecommender

In [8]:
DATA_PATH = PROJECT_ROOT / "data" / "raw"

ratings = load_ratings(DATA_PATH)
movies = load_movies(DATA_PATH)

print(ratings.shape)
print(movies.shape)

(32000204, 4)
(87585, 3)

In [9]:
trending_rec = TrendingRecommender(window_days=365)
trending_rec.fit(ratings, movies)

trending_rec.recommend(top_k=10)

,movieId,recent_rating_count,title,genres
0,79132,2946,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
1,58559,2744,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
2,109487,2721,Interstellar (2014),Sci-Fi|IMAX
3,2571,2715,"Matrix, The (1999)",Action|Sci-Fi|Thriller
4,318,2592,"Shawshank Redemption, The (1994)",Crime|Drama
5,2959,2537,Fight Club (1999),Action|Crime|Drama|Thriller
6,270698,2446,Everything Everywhere All at Once (2022),Action|Comedy|Sci-Fi
7,4993,2347,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy
8,7153,2243,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy
9,5952,2223,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy

In [10]:
for days in [30, 90, 180, 365]:
    trending_rec = TrendingRecommender(window_days=days)
    trending_rec.fit(ratings, movies)
    print(f"\nTop 5 trending movies in last {days} days:")
    display(trending_rec.recommend(top_k=5))

Top 5 trending movies in last 30 days:

,movieId,recent_rating_count,title,genres
0,79132,261,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
1,2571,243,"Matrix, The (1999)",Action|Sci-Fi|Thriller
2,58559,241,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
3,287699,236,Oppenheimer (2023),Drama
4,2959,235,Fight Club (1999),Action|Crime|Drama|Thriller

Top 5 trending movies in last 90 days:

,movieId,recent_rating_count,title,genres
0,287699,1151,Oppenheimer (2023),Drama
1,288513,939,Barbie (2023),Comedy
2,79132,850,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
3,58559,819,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
4,109487,786,Interstellar (2014),Sci-Fi|IMAX

Top 5 trending movies in last 180 days:

,movieId,recent_rating_count,title,genres
0,79132,1477,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
1,58559,1390,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
2,109487,1377,Interstellar (2014),Sci-Fi|IMAX
3,2571,1349,"Matrix, The (1999)",Action|Sci-Fi|Thriller
4,318,1281,"Shawshank Redemption, The (1994)",Crime|Drama

Top 5 trending movies in last 365 days:

,movieId,recent_rating_count,title,genres
0,79132,2946,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
1,58559,2744,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
2,109487,2721,Interstellar (2014),Sci-Fi|IMAX
3,2571,2715,"Matrix, The (1999)",Action|Sci-Fi|Thriller
4,318,2592,"Shawshank Redemption, The (1994)",Crime|Drama

In [11]:
from src.recommenders.popularity_recommender import TrendingWeightedRecommender

tw_rec = TrendingWeightedRecommender(window_days=90, min_votes=50)
tw_rec.fit(ratings, movies)

tw_rec.recommend(10)

,movieId,recent_rating_count,recent_avg_rating,trending_score,title,genres
0,318,737,4.348711,4.277335,"Shawshank Redemption, The (1994)",Crime|Drama
1,2959,741,4.298246,4.230421,Fight Club (1999),Action|Crime|Drama|Thriller
2,109487,786,4.258906,4.197085,Interstellar (2014),Sci-Fi|IMAX
3,296,637,4.249608,4.175055,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
4,202439,468,4.266026,4.165566,Parasite (2019),Comedy|Drama
5,858,496,4.255040,4.160738,"Godfather, The (1972)",Crime|Drama
6,1213,378,4.280423,4.157157,Goodfellas (1990),Crime|Drama
7,1203,232,4.338362,4.141004,12 Angry Men (1957),Drama
8,2571,766,4.195822,4.136352,"Matrix, The (1999)",Action|Sci-Fi|Thriller
9,1704,426,4.231221,4.125553,Good Will Hunting (1997),Drama|Romance

In [12]:
# testing time decay weighted treending recommender

import numpy as np

In [13]:
from src.recommenders.popularity_recommender import TimeDecayWeightedTrendingRecommender

td_rec = TimeDecayWeightedTrendingRecommender(
    lambda_decay=0.01,
    min_weight=50.0
)

td_rec.fit(ratings, movies)
td_rec.recommend(top_k=10)

,movieId,decayed_count,decayed_rating_sum,decayed_avg_rating,trending_score,title,genres
0,318,739.086418,3214.704159,4.349565,4.299891,"Shawshank Redemption, The (1994)",Crime|Drama
1,2959,739.491919,3158.050889,4.270568,4.225923,Fight Club (1999),Action|Crime|Drama|Thriller
2,1203,235.416265,1024.119993,4.350252,4.212798,12 Angry Men (1957),Drama
3,109487,782.702013,3323.840042,4.246623,4.205732,Interstellar (2014),Sci-Fi|IMAX
4,202439,484.383232,2067.994622,4.269336,4.203492,Parasite (2019),Comedy|Drama
5,296,629.225244,2666.227131,4.237317,4.187872,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
6,858,499.142100,2120.357509,4.248004,4.185872,"Godfather, The (1972)",Crime|Drama
7,1213,378.618169,1610.889516,4.254655,4.174276,Goodfellas (1990),Crime|Drama
8,1704,434.121866,1832.602691,4.221401,4.153673,Good Will Hunting (1997),Drama|Romance
9,1221,334.639735,1416.176474,4.231944,4.145327,"Godfather: Part II, The (1974)",Crime|Drama

In [14]:
for lam in [0.005, 0.01, 0.02]:
    td_rec = TimeDecayWeightedTrendingRecommender(lambda_decay=lam, min_weight=50.0)
    td_rec.fit(ratings, movies)
    print(f"\nTop 5 movies for lambda_decay={lam}")
    display(td_rec.recommend(5))

Top 5 movies for lambda_decay=0.005

,movieId,decayed_count,decayed_rating_sum,decayed_avg_rating,trending_score,title,genres
0,318,1441.951200,6267.195615,4.346330,4.319920,"Shawshank Redemption, The (1994)",Crime|Drama
1,1203,452.848052,1972.787311,4.356400,4.277040,12 Angry Men (1957),Drama
2,202439,979.303983,4190.940615,4.279509,4.244475,Parasite (2019),Comedy|Drama
3,170705,164.888476,732.472087,4.442227,4.236551,Band of Brothers (2001),Action|Drama|War
4,2959,1428.120062,6075.587885,4.254256,4.230713,Fight Club (1999),Action|Crime|Drama|Thriller

Top 5 movies for lambda_decay=0.01

,movieId,decayed_count,decayed_rating_sum,decayed_avg_rating,trending_score,title,genres
0,318,739.086418,3214.704159,4.349565,4.299891,"Shawshank Redemption, The (1994)",Crime|Drama
1,2959,739.491919,3158.050889,4.270568,4.225923,Fight Club (1999),Action|Crime|Drama|Thriller
2,1203,235.416265,1024.119993,4.350252,4.212798,12 Angry Men (1957),Drama
3,109487,782.702013,3323.840042,4.246623,4.205732,Interstellar (2014),Sci-Fi|IMAX
4,202439,484.383232,2067.994622,4.269336,4.203492,Parasite (2019),Comedy|Drama

Top 5 movies for lambda_decay=0.02

,movieId,decayed_count,decayed_rating_sum,decayed_avg_rating,trending_score,title,genres
0,318,381.435166,1656.572763,4.343000,4.252917,"Shawshank Redemption, The (1994)",Crime|Drama
1,2959,386.539794,1651.759678,4.273194,4.192160,Fight Club (1999),Action|Crime|Drama|Thriller
2,109487,399.261069,1699.799405,4.257363,4.180386,Interstellar (2014),Sci-Fi|IMAX
3,858,260.304057,1110.470755,4.266052,4.153203,"Godfather, The (1972)",Crime|Drama
4,296,328.124793,1387.259314,4.227841,4.140285,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller