In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parent
sys.path.append(str(PROJECT_ROOT))

In [3]:
from src.data.load_data import load_ratings, load_movies
from src.recommenders.hybrid_ranker import HybridRankingRecommender

In [4]:
DATA_PATH = PROJECT_ROOT / "data" / "raw"

ratings = load_ratings(DATA_PATH)
movies = load_movies(DATA_PATH)

In [5]:
hybrid_rec = HybridRankingRecommender(
    trending_window_days=90,
    lambda_decay=0.01,
    min_votes=1000,
    min_weight=50.0,
    w_popularity=0.20,
    w_weighted_popularity=0.30,
    w_recent_trending=0.20,
    w_time_decay=0.30,
)

hybrid_rec.fit(ratings, movies)
hybrid_rec.recommend(top_k=10)

,movieId,title,genres,rating_count,weighted_score,recent_rating_count,time_decay_score,hybrid_score
0,318,"Shawshank Redemption, The (1994)",Crime|Drama,102929,4.391148,737.0,4.299891,0.928063
1,296,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,98409,4.184979,637.0,4.187872,0.857759
2,2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller,93808,4.144292,766.0,4.133570,0.856712
3,2959,Fight Club (1999),Action|Crime|Drama|Thriller,77332,4.213158,741.0,4.225923,0.845013
4,356,Forrest Gump (1994),Comedy|Drama|Romance|War,100296,4.042401,610.0,4.033885,0.812397
5,593,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller,90330,4.135849,502.0,4.118139,0.800316
6,58559,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX,59334,4.153986,819.0,4.122423,0.798049
7,79132,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX,57931,4.137620,850.0,4.117184,0.797864
8,858,"Godfather, The (1972)",Crime|Drama,66440,4.297577,496.0,4.185872,0.783848
9,4993,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,73122,4.077468,657.0,4.084877,0.781034

In [7]:
# recency focused recommender

hybrid_rec = HybridRankingRecommender(
    w_popularity=0.10,
    w_weighted_popularity=0.20,
    w_recent_trending=0.30,
    w_time_decay=0.40,
)

hybrid_rec.fit(ratings, movies)
hybrid_rec.recommend(top_k=10)

,movieId,title,genres,rating_count,weighted_score,recent_rating_count,time_decay_score,hybrid_score
0,318,"Shawshank Redemption, The (1994)",Crime|Drama,102929,4.391148,737.0,4.299891,0.892094
1,2959,Fight Club (1999),Action|Crime|Drama|Thriller,77332,4.213158,741.0,4.225923,0.836697
2,2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller,93808,4.144292,766.0,4.133570,0.831671
3,296,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,98409,4.184979,637.0,4.187872,0.818732
4,79132,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX,57931,4.137620,850.0,4.117184,0.814250
5,58559,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX,59334,4.153986,819.0,4.122423,0.810060
6,109487,Interstellar (2014),Sci-Fi|IMAX,37157,4.103876,786.0,4.205732,0.796080
7,287699,Oppenheimer (2023),Drama,1152,3.582055,1151.0,4.038093,0.775520
8,4993,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,73122,4.077468,657.0,4.084877,0.766276
9,356,Forrest Gump (1994),Comedy|Drama|Romance|War,100296,4.042401,610.0,4.033885,0.765445

In [9]:
# evergreen / classic focused

hybrid_rec = HybridRankingRecommender(
    w_popularity=0.25,
    w_weighted_popularity=0.35,
    w_recent_trending=0.15,
    w_time_decay=0.25,
)

hybrid_rec.fit(ratings, movies)
hybrid_rec.recommend(top_k=10)

,movieId,title,genres,rating_count,weighted_score,recent_rating_count,time_decay_score,hybrid_score
0,318,"Shawshank Redemption, The (1994)",Crime|Drama,102929,4.391148,737.0,4.299891,0.946047
1,296,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,98409,4.184979,637.0,4.187872,0.877272
2,2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller,93808,4.144292,766.0,4.133570,0.869233
3,2959,Fight Club (1999),Action|Crime|Drama|Thriller,77332,4.213158,741.0,4.225923,0.849170
4,356,Forrest Gump (1994),Comedy|Drama|Romance|War,100296,4.042401,610.0,4.033885,0.835873
5,593,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller,90330,4.135849,502.0,4.118139,0.822917
6,858,"Godfather, The (1972)",Crime|Drama,66440,4.297577,496.0,4.185872,0.796195
7,58559,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX,59334,4.153986,819.0,4.122423,0.792043
8,79132,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX,57931,4.137620,850.0,4.117184,0.789671
9,4993,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,73122,4.077468,657.0,4.084877,0.788413